const express=require("express")
const mongoose=require("mongoose")
const hide=require("./controllers/hiddenFrontend")
const myEmployees=require("./controllers/employeesFetch")
const profileFetch=require("./controllers/profileFetch")
const companyPost=require("./controllers/Company-Post")
const employeeRegister=require("./controllers/employeeRegister")
const {absenceController,continueAbsence,logAbsence}=require("./controllers/managmentController/absenceController")
const {lateController,nameData}=require("./controllers/managmentController/lateController")
const {resignationController,statusController}=require("./controllers/managmentController/resignationController")
const overtimeController=require("./controllers/managmentController/overtimeController")
const {taskController,taskAction,taskLength}=require("./controllers/managmentController/taskController")
const {salaryNew,salaryRaise}=require("./controllers/managmentController/salaryController")
const promotionController=require("./controllers/managmentController/promotionController")
const {leaveController,logLeaveRequest}=require("./controllers/managmentController/leaveController")
const companyFetch=require("./controllers/companyFetch")
const multer=require("multer")
const upload=multer()
const path=require("path")
require("dotenv").config()
const string=process.env.STRING
const app=express()
app.use("/uploads",express.static("uploads"))
app.use(express.static(path.join(__dirname,"public")))
app.use(express.json())
app.use(express.urlencoded({ extended: true }));
mongoose.connect(string)
.then(()=>{
    console.log("DB Connected")
}).catch((err)=>{
    console.log(err)
})
app.get("/",(req,res)=>{
    res.sendFile(path.join(__dirname,"public/index.html"))
})
app.post("/myEmployees",myEmployees)
app.post("/profileFetch",profileFetch)
app.get("/companyFetch/:uid",companyFetch)
app.post("/lateController",upload.none(),lateController)
app.post("/taskController",upload.none(),taskController)
app.post("/taskAction",upload.none(),taskAction)
app.post("/taskLength",upload.none(),taskLength)
app.post("/absenceController",upload.none(),absenceController)
app.post("/overtimeController",upload.none(),overtimeController)
app.post("/promotionController",upload.none(),promotionController)
app.post("/resignationController",upload.none(),resignationController)
app.post("/leaveController",upload.none(),leaveController)
app.post("/salaryNew",upload.none(),salaryNew)
app.post("/salaryraise",upload.none(),salaryRaise)
app.get("/hide",hide)
app.post("/nameData",nameData)
app.post("/statusController",statusController)
app.post("/logAbsence",logAbsence)
app.post("/logLeaveRequest",logLeaveRequest)
app.post("/continueAbsence",continueAbsence)
app.post("/employeeRegister",upload.fields([
   { name:"profilePhoto",maxCount:1},
   { name:"document",maxCount:1}
]),employeeRegister)
app.post("/",upload.single("image"),companyPost)
app.listen(5000,()=>{
    console.log("Server Listening to Port 5000")
})